name: Deploy Site

on:
  push:
    branches: [main]
    paths:
      - 'packages/rc-ui-lib/docs/**'
      - 'packages/rc-ui-lib/src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build Site
        run: yarn build:site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: packages/rc-ui-lib/site
