# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Cache lerna
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/yarn.lock') }}
        
      - name: Install
        run: yarn bootstrap
  build-cli:
    name: build-cli
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          # codecov.io requires a fetch depth > 1.
          fetch-depth: 2

      - name: Restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/yarn.lock') }}

      - name: buliding
        run: yarn build:cli
        
    needs: setup
  test:
    name: Testing and Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          # codecov.io requires a fetch depth > 1.
          fetch-depth: 2

      - name: Restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/yarn.lock') }}

      - name: Restore cli
        uses: actions/setup-node@v2
        with:
          path: packages/rc-cli/lib
          key: ${{ runner.os }}-cli-${{ github.sha }}
          node-version: '16'
      - name: unlink node 
        run: sudo unlink /usr/bin/node
      - name: change node
        run: sudo ln -s /usr/local/bin/node /usr/bin/node
        
      - name: Test     
        run: yarn test
      
      - name: Coverage
        run: bash <(curl -s https://codecov.io/bash)
    needs: build-cli

